//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCenter.TrafficMessageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MessageService", ConfigurationName="TrafficMessageService.ITrafficMessage")]
    public interface ITrafficMessage {
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/GetServerName", ReplyAction="MessageService/ITrafficMessage/GetServerNameResponse")]
        string GetServerName();
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/GetServerName", ReplyAction="MessageService/ITrafficMessage/GetServerNameResponse")]
        System.Threading.Tasks.Task<string> GetServerNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/SendMessage", ReplyAction="MessageService/ITrafficMessage/SendMessageResponse")]
        void SendMessage(string message, int adress);
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/SendMessage", ReplyAction="MessageService/ITrafficMessage/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string message, int adress);
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/RetrieveMessage", ReplyAction="MessageService/ITrafficMessage/RetrieveMessageResponse")]
        string RetrieveMessage(int adress);
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageService/ITrafficMessage/RetrieveMessage", ReplyAction="MessageService/ITrafficMessage/RetrieveMessageResponse")]
        System.Threading.Tasks.Task<string> RetrieveMessageAsync(int adress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrafficMessageChannel : CarCenter.TrafficMessageService.ITrafficMessage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrafficMessageClient : System.ServiceModel.ClientBase<CarCenter.TrafficMessageService.ITrafficMessage>, CarCenter.TrafficMessageService.ITrafficMessage {
        
        public TrafficMessageClient() {
        }
        
        public TrafficMessageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrafficMessageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrafficMessageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrafficMessageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetServerName() {
            return base.Channel.GetServerName();
        }
        
        public System.Threading.Tasks.Task<string> GetServerNameAsync() {
            return base.Channel.GetServerNameAsync();
        }
        
        public void SendMessage(string message, int adress) {
            base.Channel.SendMessage(message, adress);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string message, int adress) {
            return base.Channel.SendMessageAsync(message, adress);
        }
        
        public string RetrieveMessage(int adress) {
            return base.Channel.RetrieveMessage(adress);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveMessageAsync(int adress) {
            return base.Channel.RetrieveMessageAsync(adress);
        }
    }
}
